### ISSUE TITLE
Really long header values get cut off.

### ISSUE THREAD

**Issue by kalbert312** [bewisse/modheader#11]
I have a very long authorization header set (`Bearer <super long token>`) and when the text length exceeds the text input length, it just gets cut off in the UI. Unlike standard input boxes, the text does not move position when clicking and dragging over the text to highlight. The only way I've found to see the entire content of the value text input is to focus the input and press navigate it with the keyboard arrows.

**Comment by jsheedy** [comment]
Just came here to say the same thing.

**Comment by hao1300** [comment]
I just released version 2.5.0 that will include a button that will allow you to edit the text in a bigger textarea.
