### ISSUE TITLE
Mac: On Multiple displays/monitors, checkboxes to activate/deactivate a modheader header don't toggle visibly but do take effect

### ISSUE THREAD

**Issue by bronius** [bewisse/modheader#14]
## How to Reproduce

1. On Mac Mojave with multiple monitors active and Chrome browser in secondary monitor
1. Click extension icon to modify headers: See modheaders dialog show.
1. Click to check an existing, unchecked checkbox: Expected, checkbox should show checked. **Instead:** See that the checkbox still appears unchecked.
1. Dismiss the dialog.
1. Click to show the modheaders dialog again. See that that pesky checkbox **is** checked after all!
1. Click to uncheck that checkbox: .. you know what's next :)

The same can be repeated for checking or unchecking the checkboxes.

Thanks for this terrific little extension! Works like a charm!

**Comment by hao1300** [comment]
I don't have the luxury of having multiple monitors on Mac to reproduce this, but FWIIW, I just updated the UI library dependency. There is a chance that this issue might get fixed with that update.

**Comment by bronius** [comment]
..and I haven't had a second monitor for a while..

Thanks for looking into this. I'll mark it Closed so it's off your mind. If I find myself in a position to test it, I'll share outcome here.

Thanks for sharing this nifty little extension. Cheers!
