### ISSUE TITLE
not working with FF71+

### ISSUE THREAD

**Issue by n8v8R** [bewisse/modheader#16]
* FX 72.0a1 (2019-11-11) (64-bit)
* W10 Pro x_64 v1903 b18362.449
* MH 2.4.1
____
Moz may introduce code changes with FX 72 that renders the WX unusable, least testing it with a maiden FX 72 profile would indicate so.

Neither get the headers set in the WX being applied nor is possible im/export or setup multiple header profiles.

With FX 71.0b8 (64-bit) the issue is not present.

**Comment by BenjaminBellamyJG** [comment]
Issue is that -> TypeError: CHROME_VERSION is undefined

**Comment by n8v8R** [comment]
It would seem to be a bug then then in background.js?

```
  // Chrome 72+ requires 'extraHeaders' to be added for some headers to be modifiable.
  // Older versions break with it.
if (CHROME_VERSION.major >= 72) {
      for (let header of currentProfile.headers) {
        if (EXTRA_REQUEST_HEADERS.has(header.name.toLowerCase())) {
          requiresExtraRequestHeaders = true;
          break;
        }
      }
    }
```

With 

`const CHROME_VERSION = getChromeVersion();`

and

```
function getChromeVersion() {
  let pieces = navigator.userAgent.match(/Chrom(?:e|ium)\/([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9]+)/);
  if (pieces == null || pieces.length != 5) {
      return undefined;
  }
  pieces = pieces.map(piece => parseInt(piece, 10));
  return {
      major: pieces[1],
      minor: pieces[2],
      build: pieces[3],
      patch: pieces[4]
  };
}

there is probably a bug then.
```

**Comment by SubZtep** [comment]
No sign of the extra headers to me as well when I installed from Mozilla's extension store. Got curious and downloaded the current master branch, loaded as a _Temporary Add-on_, and it worked! 😮 `v71.0b12`

**Comment by n8v8R** [comment]
Seems than that FF code causing the issue is riding the trains and has arrived in the beta branch (now 71). And code merge to FF stable branch (then 71) is scheduled in a couple of days (2019-12-02).

Comparing the last commit date in this WX's master branch (13 Oct) vs. AOM store (Jul 14) there is a bit of discrepancy, wondering why it is not being merged into a AOM store release.

**Comment by n8v8R** [comment]
FF71 been released and the WX has turned useless now

**Comment by hao1300** [comment]
Firefox pulled the newer versions of ModHeader from their web store. They were complaining that it includes minified version of AngularJS and other AngularJS UI scripts that were not meeting their expectations. I still haven't had time to resolve the issues with them :(

**Comment by hao1300** [comment]
Newer version is published. Hopefully Mozilla won't pull it out again this time.
