### ISSUE TITLE
How to conditionally apply headers?

### ISSUE THREAD

**Issue by borekb** [bewisse/modheader#18]
For URLs `/example-1/*`, I want to add a header `x-my-header: 1`.
For URLs `/example-2/*`, I want to add a header `x-my-header: 2`.

Is there a way to do it? I can create multiple profiles but I'd need to be switching them constantly, right? Thanks.

**Comment by borekb** [comment]
The UI suggests that I can select multiple profiles but they seem to be mutually exclusive (the checkboxes behave like toggle buttons).

<img width="253" alt="Screenshot 2019-12-05 at 11 24 01" src="https://user-images.githubusercontent.com/101152/70226838-d31e7580-1751-11ea-97d4-491f13db153f.png">

**Comment by hao1300** [comment]
There is no way to do it currently. I have updated the UI to stop using checkbox for profiles.

**Comment by hao1300** [comment]
We now support dynamic header value (See https://bewisse.com/modheader/help/ - How do I set a dynamic value). You can now write a custom function to return different value based on URL.
