### ISSUE TITLE
Don't change case on headers

### ISSUE THREAD

**Issue by tibbon** [bewisse/modheader#19]
In Chrome, I'm seeing a header like `Foo-Bar` get turned into `foo-bar`. That doesn't work for me as I have specific casing I need with this one API I'm using. I see in the code an area that's setting everything to lower-case. Can we not do that?

**Comment by 278kunal** [comment]
Can this be please added, as there are scenario where I want my headers to be in the case as added. If you want I can take this feature.

**Comment by hao1300** [comment]
This is not possible as it is the browser that is changing the header's case. We try to keep the header case as is, and it is actually preserved in Firefox with the same codes, but Chrome is opinionated and likes to change all custom headers to lower-case. I can't fix it for Chrome.
