### ISSUE TITLE
profile management flyout not working with FF72+

### ISSUE THREAD

**Issue by n8v8R** [bewisse/modheader#20]
* W10 Pro x_64 v1909 b18363.476
* FF x_64 v 72 (currently beta) | 73 (currently nightly) - either with a maiden profile
* MH 2.5.0
____
opening the profile management flyout (upper right) generates a miniature window that jumps up and down

![Annotation 2019-12-08 000403](https://user-images.githubusercontent.com/13611490/70381678-ad0df680-1946-11ea-9137-0cc3e17ed1af.png)

**Comment by hao1300** [comment]
Thank you for your report. Just uploaded a fix in 2.5.1. Should show up once Mozilla approves it.
