### ISSUE TITLE
profile management flyout not working when the WX's main window size is exceeded

### ISSUE THREAD

**Issue by n8v8R** [bewisse/modheader#21]
* W10 Pro x_64 v1909 b18363.476
* FF x_64 v 71 (maiden profile)
* MH 2.5.0
___
After having imported two profiles the profile management flyout (upper right) generates a blank strip only.

![Annotation 2019-12-08 141906](https://user-images.githubusercontent.com/13611490/70389889-58599280-19bd-11ea-804f-9d4471fc5e7e.png)

**Comment by hao1300** [comment]
Thank you for your report. Just uploaded a fix in 2.5.1. Should show up once Mozilla approves it.

**Comment by n8v8R** [comment]
I am afraid the issue is still present after the update to 2.5.1. From the debugging console when opening the flyout

>mdMenu: The $mdOpenMenu method is deprecated. Please use `$mdMenu.open`.  angular.min.js:127:303
___
Other issues observed in the printout of the debugging console

>Content Security Policy: The page's settings blocked the loading of a resource at eval ("script-src"). angular.min.js:formatted:5961   

>The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. popup.html

>Markup '<md-button flex></md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details. 2 angular.min.js:formatted:3577

>Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://98f93197-a0cc-4491-a962-f44154c955fa/scripts/angular.min.js
Source Map URL: angular.min.js.map

https://developer.mozilla.org/en-US/docs/Tools/Debugger/Source_map_errors

**Comment by hao1300** [comment]
That is strange. Were you still seeing issue https://github.com/bewisse/modheader/issues/20 as well, or only this one? Are you seeing this in the stable FF 71 or FF 72 beta? I am  not able to reproduce this :-/

The other issues in the console log should be unrelated, though I will get to them someday.

**Comment by n8v8R** [comment]
The bouncing flyout as reported in #20 is not exhibited in FX72+ anymore but it exhibts now the same issue as reported in this thread.

This is after the WX installation with a maiden profile in FX71 x_64

![Annotation 2019-12-09 121817](https://user-images.githubusercontent.com/13611490/70431819-22301780-1a7e-11ea-9311-8da95dabc5ed.png)

The I import multiple profiles _(exported from Chrome)_ and switch to one of the imported profile and then getting this

![Annotation 2019-12-09 121817](https://user-images.githubusercontent.com/13611490/70432151-da5dc000-1a7e-11ea-9592-e929ea252a2f.png)

Switching back to _empty Profile 1_ that comes with the WX installation the issue not exhibited.

**Comment by n8v8R** [comment]
The issue appears to be caused by the size of the flyout window, respectively exceeding its size or number of rules - not quite sure which

Using the _empty Profile 1_ that comes with the WX installation as sole profile. The adding (empty) header or filter rules until the flyout window is filled (in this case 11 of such rules) and the issue is being triggered.

Since I would not expect the number of rules being somewhat limited I reckon the bug is triggered by exceeding the size of the flyout window, which might be different on different screen resolutions.

Hope that helps to find the code culprit and get it sorted...

**Comment by hao1300** [comment]
Thank you for the repro steps! I think https://github.com/bewisse/modheader/commit/f08abaca652d502fa4fde4e8cf5d364720b09673 should fix it. Can you give it a try before I release it?

**Comment by n8v8R** [comment]
downloaded modheader-master.zip but installation fails with

> File modheader-master.zip does not contain a valid manifest

**Comment by hao1300** [comment]
can you unzip, and point Firefox to src/manifest.json?

**Comment by n8v8R** [comment]
that worked. with the commit the issue does not reproduce any more, test with FX 71 & 73
