### ISSUE TITLE
Request Headers Not Being Sent

### ISSUE THREAD

**Issue by JasonMiller** [bewisse/modheader#22]
# Environment
Latest Chrome Version 78.0.3904.108
Latest Version of the Extension 2.5.3

# Steps to Reproduce
Add Request Header overrides
Refresh
Open the network tab of Chrome developer tools
Select any requested asset
In the headers tab, see that no overrides are present

# Notes
Also reproduced on Firefox

**Comment by EltonFaust** [comment]
Same here (chrome 78) was working 2 hours ago, aparently is a bug from the latest verion

**Comment by EltonFaust** [comment]
Hey, @JasonMiller try to restart your chrome, worked with me

**Comment by JasonMiller** [comment]
Well dang. Didn't even think to jiggle the handle. Closing out.
