### ISSUE TITLE
Newest update broke extension - no longer adds headers

### ISSUE THREAD

**Issue by jtheberge** [bewisse/modheader#23]
Hello, I noticed the newest update has broken the extension. I am on Chrome `Version 78.0.3904.108 (Official Build) (64-bit)`
![image](https://user-images.githubusercontent.com/13157499/70655567-5259f080-1c0d-11ea-8c3d-3779a856d316.png)

**Comment by bhmiller** [comment]
Probably a duplicate of #22 . from that - restart chrome.

**Comment by jtheberge** [comment]
lgtm now, 😆 thank you
