### ISSUE TITLE
[bug] response header not working with FF71+

### ISSUE THREAD

**Issue by n8v8R** [bewisse/modheader#25]
* W10 Pro x_64 v1909 b18363.535
* FX x_64 71+ with maiden profile
* MH 2.5.3
____
None of set response header rules getting applied/injected. Exported the rule set to Chrome where it works as expected.

**Comment by jtheberge** [comment]
Probable duplicates of
https://github.com/bewisse/modheader/issues/22
https://github.com/bewisse/modheader/issues/23

Restarting browser fixed for me

**Comment by n8v8R** [comment]
updated MH to v2.5.4 and restarted the browser, profile settings at the bottom. Tried all override modes and the result is that sometimes it works and sometimes not (contratry to request headers which always work).

Observations:

* never works on the first response

![Annotation 2019-12-12 091833](https://user-images.githubusercontent.com/13611490/70694636-66125f00-1cc0-11ea-95d3-f3f6977023d0.png)

* sometimes works as expected

![Annotation 2019-12-12 091833](https://user-images.githubusercontent.com/13611490/70694748-a376ec80-1cc0-11ea-8cbb-917b860e9e09.png)

* and often other times it does not (missing headers entirely and/or not overriding)

![Annotation 2019-12-12 091833](https://user-images.githubusercontent.com/13611490/70695046-28620600-1cc1-11ea-8342-398c078c30e5.png)
____
`{"title":"Profile 1","hideComment":true,"headers":[{"enabled":false,"name":"","value":"","comment":""}],"respHeaders":[{"enabled":true,"name":"Feature-Policy","value":"feature-policy: accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; battery 'none'; camera 'none'; display-capture 'none'; execution-while-not-rendered 'none'; execution-while-out-of-viewport 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; speaker 'none'; usb 'none'; wake-lock 'none'; xr-spatial-tracking 'none'","comment":""},{"enabled":true,"name":"ETag","value":"\"\"","comment":""},{"enabled":true,"name":"X-DNS-Prefetch-Control","value":"off","comment":""}],"filters":[],"urlReplacements":[],"appendMode":true}`

**Comment by hao1300** [comment]
Response headers don't show up in the network tab because they are modified *after* the response was received from the wire. To help make this easier to see, I have created a page on https://bewisse.com/modheader/headers/ where you can see the response headers as can be seen by the JS client. Give it a try and let me know if it is still broken for you.

Note that there are some headers that the browser will look at even before giving them to ModHeader. In which case the modification would come too late.

**Comment by n8v8R** [comment]
Thank you for the effort of having created that page. The issue is not exhibited there, however that said - the issue does not exhibit in Chrome - there it works as expected (display in the browser console)?

**Comment by hao1300** [comment]
Well, Chrome used to not support that in the network tab either. I don't know when they added it, but it is nice that they did. I don't know when Firefox will support it (or if they ever will). If your client is able to see it now, shall we close the issue?

**Comment by n8v8R** [comment]
Suppose so
