### ISSUE TITLE
[bug] FX 71+ wrong setting storage (Window.localStorage vs. storage.local)

### ISSUE THREAD

**Issue by n8v8R** [bewisse/modheader#27]
* W10 Pro x_64 v1909 b18363.535
* FX x_64 71+ with maiden profile
* MH 2.5.4
____
It is observed that clearing browser history with

* [x] Cookies
and/or
* [x] Offline Website Data

the WX settings are getting cleared which is unepexted and should not happen.

![screen cast](https://user-images.githubusercontent.com/13611490/70699541-990d2080-1cc9-11ea-8ddf-2b17059da34d.gif)

Another observation is that uninstalling the WX and reinstalling it (even with restarting the browser in between) the WX settings from the previous installation are still present which is also unepexted and should not happen.

Other WX in comparision do not exhibit the issue.

According to <sup>**1**</sup>:

>it is recommended that you don't use Window.localStorage in extension code. Firefox will clear data stored by extensions using the localStorage API in various scenarios where users clear their browsing history and data for privacy reasons, while data saved using the storage.local API will be correctly persisted in these scenarios.

___
<sup>**1**</sup> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local

**Comment by hao1300** [comment]
Fixed in version 3.0
