### ISSUE TITLE
[feature suggestion] strip/cancel header name

### ISSUE THREAD

**Issue by n8v8R** [bewisse/modheader#28]
It would be useful if a header name (and subsequent its value) could cancelled/stripped altogether instead (as opposed to) of overriding the value.
___
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest

> On some of these events, you can modify the request. Specifically, you can:
> 
>     cancel the request in:
>         onBeforeRequest
>         onBeforeSendHeaders
>         onAuthRequired
___
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest

>to cancel the request, include a property cancel with the value true
___
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onAuthRequired

>in the listener itself, return an object with a cancel property set to true

**Comment by hao1300** [comment]
Just leave the value field to be empty. That will remove the header from being sent. The `cancel` property will cancel the whole request, which isn't desired in most cases.
