### ISSUE TITLE
[feature suggestion (or bug?)] combine/utilize multiple profiles

### ISSUE THREAD

**Issue by n8v8R** [bewisse/modheader#29]
Not sure if it is meant already implemented and just not working or else it would be handy to utilize multiple profiles for use case:

* have a global profile
* additional fine grain profile(s) with specific URL and/or filter

Currently however selecting multiple profiles is not working (neither wit FX or Chrome with MH 2.5.4), always reverts/toggles to a single profile (cross reference https://github.com/bewisse/modheader/issues/18#issuecomment-562067261)

![screen cast](https://user-images.githubusercontent.com/13611490/70817333-a4e40a00-1dd1-11ea-9045-be97e0c3d14b.gif)

**Comment by hao1300** [comment]
@n8v8R as of v3.1.3, we now support multiple active profiles. You can right click on a profile on the left drawer, and select "Always stay on". This will allow that profile to stay active even when you select another profile, and you will see a green checkbox at the bottom right hand corner.
