### ISSUE TITLE
[bug] impossible to create profile with no response header

### ISSUE THREAD

**Issue by n8v8R** [bewisse/modheader#30]
* W10 Pro x_64 v1909 b18363.535
* FX x_64 71+ with maiden profile
* Chrome x_64 Canary 80.0.3987.7 dev
* MH 2.5.4
____
![screen cast](https://user-images.githubusercontent.com/13611490/70819610-f17e1400-1dd6-11ea-86de-cb6b6a6f61e6.gif)

**Comment by hao1300** [comment]
That is working as intended actually. Most people install ModHeader to modify the request header, not to create an empty profile. The most likely next action after they clear the profile is to add a new request header. I basically optimize that action.
