### ISSUE TITLE
[rfi] header override modes

### ISSUE THREAD

**Issue by n8v8R** [bewisse/modheader#31]
Having looked into the source code and the HELP section I might have failed to grasp the concept (find clues) of header override modes:

* value concatenation 
* comma separated concatenation

I could only suppose that each is sort of an append mode to existing request or response header? 
Thus this RFI to get a better understanding of how each mode is panning out.

**Comment by hao1300** [comment]
Updated https://bewisse.com/modheader/help/ to clarify various Append Mode. Let me know if they make sense.
