### ISSUE TITLE
[feature suggestion] add client hints reponse headers to autocompleteService.requestHeaderNames

### ISSUE THREAD

**Issue by n8v8R** [bewisse/modheader#32]
remote server can opt in the client <sup>**[1]**</sup>, either via:

1. response header
or
1. HTML meta element with the http-equiv attribute

into following request headers:

* Device-Memory<sup>**[2]**</sup>
* DPR<sup>**[3]**</sup>
* Content-DPR<sup>**[4]**</sup>
* Width<sup>**[5]**</sup>
* Viewport-Width<sup>**[6]**</sup>
* Downlink<sup>**[7]**</sup>
* Save-Data<sup>**[8]**</sup>
___
<sup>**[1]**</sup> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers#Client_hints
<sup>**[2]**</sup> https://github.com/w3c/device-memory
<sup>**[3]**</sup> https://tools.ietf.org/html/draft-grigorik-http-client-hints-03#section-3
<sup>**[4]**</sup> https://tools.ietf.org/html/draft-grigorik-http-client-hints-03#section-3.1
<sup>**[5]**</sup> https://tools.ietf.org/html/draft-grigorik-http-client-hints-03#section-4
<sup>**[6]**</sup> https://tools.ietf.org/html/draft-grigorik-http-client-hints-03#section-5
<sup>**[7]**</sup> https://tools.ietf.org/html/draft-grigorik-http-client-hints-03#section-6
<sup>**[8]**</sup> https://tools.ietf.org/html/draft-grigorik-http-client-hints-03#section-7

**Comment by hao1300** [comment]
Added in version 3.0.3
