### ISSUE TITLE
[feature proposal] Take data from local storage and use variables in headers values 

### ISSUE THREAD

**Issue by HerlinMatos** [bewisse/modheader#33]
Eg: I have a token saved in my local storage, It's saved every time a logged-in my page, so I have to copy and paste every time in the Authorization header, I would like to have an option to use variables within headers with the token.

**Comment by hao1300** [comment]
We now support dynamic value. You can use it to generate a dynamic header. e.g., you can set the following value for Authorization:
```
function({ url, oldValue }) {
  if (url.startsWith('<some_url>')) {
    return localStorage.auth;
  }
  return oldValue;
}
```

The only probably is that localStorage is the extension's localStorage, not your page's localStorage. If the Authorization token is available somehow in some response / url, you can use dynamic value to save it to localStorage and then retrieve it like the trick above.
