### ISSUE TITLE
Not obvious how to apply header to multiple URL patterns

### ISSUE THREAD

**Issue by patrakov** [bewisse/modheader#34]
I have created an "English Please" profile, added "Accept-Language" header, its value, and set the URL pattern for one site that has incomprehensible machine-translated content. Now there is another site that I want to force to English. However, the UI is very non-intuitive regarding how to add a second URL pattern. For now, I have extended the regular expression using the "|" syntax, but ideally this should be more obvious or, as a minimal fix, the example placeholder should feature a regular expression that contains a "|".

**Comment by hao1300** [comment]
You can just add multiple URL patterns. URL pattern filters are union, not intersection, so you can simply add two URL patterns.
