### ISSUE TITLE
URL replacements set "origin: null" cause CORS fail

### ISSUE THREAD

**Issue by zizifn** [bewisse/modheader#35]
For example,
I'm in "https://weibo.com/",
I need replace URL "https://wx2.sinaimg.cn/mw690/54174acfgy1gczhs5d8yrj20m80m8q5o.jpg" to "https://wx4.sinaimg.cn/mw690/54174acfgy1gczhs3qjjgj20m80m8whr.jpg" by using "URL replacements".

But Chrome(Version 78) will have CORS error,
`
Access to fetch at 'https://wx4.sinaimg.cn/mw690/54174acfgy1gczhs3qjjgj20m80m8whr.jpg' (redirected from 'https://wx2.sinaimg.cn/mw690/54174acfgy1gczhs5d8yrj20m80m8q5o.jpg') from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`

I found when modheader doing the `307 Internal Redirect`, replacement target URL HTTP request `origin` is null. This will cause CORS error. Below is the target URL HTTP request,
![image](https://user-images.githubusercontent.com/1803942/77077494-42ce1d00-6a30-11ea-994a-7cc4efc7fb6a.png)

**Comment by hao1300** [comment]
You will likely need to set Access-Control-Allow-Origin: * in the response header (and maybe other configurations in the response headers too)

**Comment by hao1300** [comment]
Closing this issue. Please reopen if necessary.
