### ISSUE TITLE
Install and configure through chrome launch args?

### ISSUE THREAD

**Issue by oskbor** [bewisse/modheader#37]
Hi, 
Not sure on where to turn for my question, so I am starting here.
I want to launch chrome via its CLI and have it install modheader and also configure one or two headers. Do you know if that is possible and how to do it in that case? Im trying to use this extension in our CI system.

Thank you for an awesome plugin!

br Oskar

**Comment by hao1300** [comment]
If you need ModHeader for Selenium WebDriver, please try using https://github.com/bewisse/modheader_selenium. I have some examples there. You can install extensions in WebDriver. No need to change the Chrome launch args.
