### ISSUE TITLE
Errors loading legacy directory

### ISSUE THREAD

**Issue by justincalleja** [bewisse/modheader#38]
I have tried loading the `legacy` directory by enabling dev mode in Chrome extensions -> Load unpacked -> select `legacy` directory.

I get the following UI and angular error messages shown in screenshots. Is this how to load v2?

Thanks

![image](https://user-images.githubusercontent.com/9398504/79123737-17262480-7d9b-11ea-8bde-465b7fedff36.png)

![image](https://user-images.githubusercontent.com/9398504/79123688-fcec4680-7d9a-11ea-9a41-f581187c4db9.png)

**Comment by hao1300** [comment]
Hi, the legacy codes are no longer supported and have been removed from the repo. If there is something that you would like to have in V3, please file a separate issue. Unfortunately I won't be supporting the legacy codes.

**Comment by justincalleja** [comment]
Ok thanks @hao1300
