### ISSUE TITLE
ModHeader Freezes when adding URL Pattern Filter

### ISSUE THREAD

**Issue by taclayto** [bewisse/modheader#39]
Opening ModHeader and attempting to add a URL Pattern filter causes the addon to freeze. 

I'm using the following Regex Pattern
.*\.test1.com.*|.*\.test2.com.*|.*\.longurllongurllongurltest3-test.com.*|.*\.longurllongurllongurltest4-test.com.*
(replaced real URLs with placeholders) 

Edit: Chrome Version: 80.0.3987.163 (Official Build) (64-bit)
ModHeader Version: 3.0.0

**Comment by hao1300** [comment]
I pushed out a fix in 3.0.3. Please give it a try and let me know if it is fixed.

**Comment by taclayto** [comment]
@hao1300 Yes, it looks fixed. Thank you so much!
