### ISSUE TITLE
UI Issues: Navigation bar gets in way, profile sections cause clutter, badge issues and etc.

### ISSUE THREAD

**Issue by patricknelson** [bewisse/modheader#40]
First of all, thank you very much for providing this useful plugin. I'm only submitting this _because_ I find it so helpful and because I use it so regularly (meaning I care about the usability of the plugin, at least for my use cases). 

Other [recent reviews on the extension](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj) seem to agree with a few of the points below (particularly on the left side navigation, see last point).

## Left navigation constantly overlapping main UI

Annoyingly, every single time I go to move my mouse over the left side of the plugin (to intentionally interact with it *or not*) it will appear and never go away. The solution to this is not to put it on a timer per se, but instead to to simply *keep it closed* and instead require an interaction to expand it temporarily (e.g. a right arrow). Also I'd strongly recommend the use of `title` attributes
 to provide hints/context as to what each profile is, which is much less invasive. This is _very important_ IMHO because it's much too easy to move your mouse over that navigation only to have it cover the very headers that you're visually trying to reference. Then every single time you interact with the extension you have to _very carefully move your mouse_ down and then out from the extension in order to prevent it from covering the headers for your visual reference! 

Again, I think the best solution for this would be a UI component, maybe an arrow like `»`, to expand the menu so you can see the full context _if you want to see it_ and then maybe a left arrow `«` to collapse it again (or any sort of interaction with main UI outside of that pop-out menu). 

![2020-04-13_10-53-03](https://user-images.githubusercontent.com/4269377/79145565-b7695280-7d75-11ea-8503-d14235b01cf5.gif)

## Profile sections:

I personally only ever use the request headers (rarely response headers). So ever since the new update, I've been noticing extra clutter in my profile containing headings that I'll never use that always remain at the very bottom of my list (meaning entries that I do use and interactive, e.g. a custom request header, will never be at the bottom). For me it's unnecessary to see these unless I need them. 

While it does reduce the amount of clicks to add a new type of header, it's an edge case for me (since I never use it). So the net effect of this new layout is that it just adds more visual clutter and increases the effort 

![image](https://user-images.githubusercontent.com/4269377/79143394-090fde00-7d72-11ea-91f4-a80b09268c53.png)

## Badges

What meaning does the number badge carry? Should it not represent the number of headers (and etc) that are currently enabled? In order to get rid of this "1" badge on the plugin, I have to completely disable the plugin.

In this example, I have 3 headers in use, yet for some mysterious reason it only ever shows `1` or nothing at all. This is very confusing.

![2020-04-13_10-49-55](https://user-images.githubusercontent.com/4269377/79144801-6d33a180-7d74-11ea-8d78-8cca2371a628.gif)

## "ModHeader is Paused" nag screen

Also, when disabling ModHeader to compensate for this erroneous badge number (above) I've noticed that I have a constant reminder that ModHeader is disabled and that I can resume it. If I close that out, because I know how to use the plugin, it never stays gone. It is convenient to use, but visually (from a UI perspective) it's redundant and distracting and because it's able to be closed it seems to me that it should *remember that it can be closed*, especially once you've already closed it after the last time the extension was paused (once resuming and pausing again, it's fine if it displays once more).

I propose either:
1. Get rid of the close button, because it serves no purpose except to increase clicks (and it's not remembered)
1. Remember the setting to close the dialog so it doesn't appear again
1. Add an option to disable it completely

![2020-04-13_10-45-36](https://user-images.githubusercontent.com/4269377/79144507-ee3e6900-7d73-11ea-92ac-80d19be8423f.png)

**Comment by hao1300** [comment]
Thanks for the feedbacks! I have revised the UI to address many of the issues listed. Version 3.0.2 is released with the fix. The one issue that I haven't addressed in the profile sections being too cluttered. I will need to think more about it.

**Comment by patricknelson** [comment]
Ok thanks @hao1300 for the consideration. Basically I like the idea of rebuilding this in Svelt, but the original UI that you had for this was perfect and didn't seem to need any improvement or changes at all.

**Comment by patricknelson** [comment]
p.s. Just tried this out and it looks much better! Thanks again for the super responsive update :)
