### ISSUE TITLE
Version for Microsoft Edge is old

### ISSUE THREAD

**Issue by ChanthMiao** [bewisse/modheader#41]
I have install this powerful extension both in edge and chrome. 
Yet the version for Edge is old (v2.5.4, installed from Microsoft extension store). The version for chrome is v3.0.1 currently.

**Comment by hao1300** [comment]
This is because Edge goes through a very lengthy review process to approve a new add-on. I submit to both stores at the same time, but Chrome has released a new version with several minor fixes while Edge is still pending.

**Comment by ChanthMiao** [comment]
Sorry for my misunderstanding. Thanks for your great work.
