### ISSUE TITLE
Long delay when typing value of request header

### ISSUE THREAD

**Issue by justincalleja** [bewisse/modheader#42]
When typing in the input field of a request header, it takes ModHeader a long time to show the value just typed. This does not apply to the key portion, only the value of request header.

This is out of the box on a new ModHeader installation.

Thank you

**Comment by rolandas-valantinas** [comment]
Not a functionality, but joke! Please revert to original release until this becomes somewhat usable!
![Screen Recording 2020-04-14 at 15 46 27](https://user-images.githubusercontent.com/6222540/79238844-c7f9f580-7e67-11ea-9536-5c920cc33128.gif)

**Comment by hao1300** [comment]
I push out a fix in version 3.0.3 earlier today. Can you give it a try and see if the problem still exist?

**Comment by kallebornemark** [comment]
Problem persists for me in 3.0.3.

**Comment by rolandas-valantinas** [comment]
Exactly the same - only re-renders faster if you move mouse around

**Comment by hao1300** [comment]
Just pushed out another optimization in v3.0.4. Please let me know if the problem still persists.

**Comment by rolandas-valantinas** [comment]
Sorry for long delay, on rare occasions it still doesn't register placing cursor or there is delay on text select. But I can't consistently replicate these issues
Very commendable progress 👍

**Comment by hao1300** [comment]
Awesome. I am closing this issue.
