### ISSUE TITLE
Stops working randomly

### ISSUE THREAD

**Issue by lehphyro** [bewisse/modheader#43]
It seems the latest chrome update on linux makes the extension stop adding headers after a few requests, the only way to make it work again is by restarting chrome.
This other extension doesn't have this issue: https://chrome.google.com/webstore/detail/modify-headers-for-google/innpjfdalfhpcoinfnehdnbkglpmogdi

**Comment by hao1300** [comment]
I just push out a bug fix for this in version 3.0.5. You can go to chrome://extensions/ and click on Update to update to the latest version. Let me know if you still run into this issue in the new version.

**Comment by lehphyro** [comment]
It seems to be working fine, thanks.
