### ISSUE TITLE
clean interface?

### ISSUE THREAD

**Issue by TerraSkye** [bewisse/modheader#44]
where did the nice and clean interface go? 
now we have an ugly not userfriendly one....

**Comment by cupofjoakim** [comment]
I have no issue with it, but "Lock Tab" was my most used functionality and I really don't like that one being hidden :/

**Comment by hao1300** [comment]
Thanks for the feedbacks! I am bring back the Lock Tab icon to the top bar. I have also cleaned up the new interface a bit. I just published version 3.0.6 with these fixes and should be live in a few hours. You may need to go to chrome://extensions/ to request a quicker update.

**Comment by cupofjoakim** [comment]
@hao1300 from my perspective this is good now. Might not look as clean as before, but there's a bit more stuff as well :)

@TerraSkye Do you have more specific feedback on what this issue should track? Looking at the original post, it's kind of hard to know what you think needs to be fixed.

**Comment by TerraSkye** [comment]
@hao1300 
- spacing, it is currently very packed and put tightly together which means its not as clean as it could be
- actions, you have action around the whole UI left,top,right which lose the focus on what your actual doing.
- i personally liked the vibrant blue color default by materialize, instead of this color schema, its very dark now
