### ISSUE TITLE
[minor UI bug] wrong overlay (undo) for adding a rule

### ISSUE THREAD

**Issue by n8v8R** [bewisse/modheader#45]
* W10 Pro x_64 v1909 b18363.778
* FX x_64 v 75 - 77
* G Chrome x_64 v 83.0.4103.14
* M Edge x_64 83.0.478.5
* MH 3.0.5 on FX & GC | 3.0.3 on ME
___
![Annotation 2020-04-16 151923](https://user-images.githubusercontent.com/13611490/79461021-213b6380-7fe5-11ea-85e6-16f864267759.png)

**Comment by hao1300** [comment]
Thanks for the report! I just pushed out a fix in 3.0.6
