### ISSUE TITLE
[ui bug] FX viewport not fitting content

### ISSUE THREAD

**Issue by n8v8R** [bewisse/modheader#46]
- W10 Pro x_64 v1909 b18363.778
- FX x_64 v 77
- G Chrome x_64 v 83.0.4103.14
- MH 3.0.5 
___
viewport on FX

![Annotation 2020-04-16 152551](https://user-images.githubusercontent.com/13611490/79461571-de2dc000-7fe5-11ea-8980-4ef5735dcd4e.png)

vs viewport on GC

![Annotation 2020-04-16 152551](https://user-images.githubusercontent.com/13611490/79461707-0fa68b80-7fe6-11ea-887f-5bf8793f5842.png)

**Comment by hao1300** [comment]
Thanks for the report! I just pushed out a fix in 3.0.6
