### ISSUE TITLE
In some cases the header is not modiffied

### ISSUE THREAD

**Issue by Haktes** [bewisse/modheader#47]
Hello,

we have a problem with headers , in **some cases** they are not modified.
_(Our backend verifies if request headers are added, if not -> 403)_
We use ModHeaders for a long time and this is a new issue to us.

Best example is when a **LINK** is opened from chat or mail then this happens.
Sometimes when a download is opened in new window but this is harder to reproduce, it does not happen all the time.
In both cases  refresh of the page helps (after refresh it works as expected)

Tested in google chrome.

**Comment by hao1300** [comment]
Thanks for the report! This is very strange. Do you mind sharing your ModHeader profile and some more detail steps on how to reproduce? AFAICT, I didn't change anything in the core header modification logics that can result in such non-determinism, but maybe I am missing something.

**Comment by martvalja** [comment]
Hi, we have also encountered the same behaviour, profile (edited header names/values, but the gist is the same):
[{"appendMode":"","backgroundColor":"#801077","filters":[],"headers":[{"comment":"","enabled":true,"name":"x-userid","value":"myuser"},{"comment":"","enabled":true,"name":"custom-user","value":"customuservalue"},{"comment":"","enabled":true,"name":"some-id","value":"mart:0.1"}],"hideComment":true,"respHeaders":[],"shortTitle":"1","title":"Custom-headers","urlReplacements":[]}]

In our case the url is called via javascript like this:
            window.open('relative/url/for/file/download.do', '_blank');

Sometimes the headers are added, sometimes not, we haven't found any pattern so far.

This problem was first noticed at 15.04.2020, but that specific feature is not used very often, so it might have been there for some time before that as well.

We are currently all using Chrome Version 80.0.3987.163 (Official Build) (64-bit) and ModHeader version 3.0.7

Hopefully this makes it easier to track it down.

**Comment by hao1300** [comment]
@martvalja @keittehvan - Thank you for the extra details. That was very helpful!

Let me summarize all information provided so far:
1) Without changing ModHeader's profile's values, the headers may be added non-deterministically
2) This may or may not be a new issue. It was just discovered last week.
3) According to a similar report on the Chrome web store, this does not reproduce when the Chrome developer tool is shown.
4) Refresh on the page will fix the issue temporarily

These lead me to leave that the browser caches is at play here. If there is a problem with ModHeader profile saving logics, it would be more deterministic, and would not work upon refresh, and also wouldn't have different behavior when the Chrome developer tool is shown. On the other hand, if the browser cache is at fault, then it would explain when it works consistently with (3) and (4).

Can you try adding "Cache-Control: no-store" or "Cache-Control: no-cache" to your Request Header to see if that helps?

**Comment by MoazAlkharfan** [comment]
I'm experiencing the same issue
The header i'm trying to change is "Host" I've tried it with caches disabled
When i add any other test header it gets appened into the headers but not the "Host" header.

**Comment by hao1300** [comment]
@MoazAlkharfan The "Host" header is only modifiable in HTTP/1.1 request, not HTTP2 requests. e.g., you can see from the network request that the modified "Host" header is sent if you visit http://xhaus.com/headers (HTTP/1.1), but you will not see the "Host" header if you visit https://bewisse.com/modheader/headers/ (HTTP2). The previous version of ModHeader has the same behavior. This is enforced by the browser, not ModHeader.

Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host

**Comment by MoazAlkharfan** [comment]
So, i ran the same test i did before but this time on chrome version "81.0.4044.129" and it works as expected.
I guess there was a bug that was resolved 😒

**Comment by yoerivdm** [comment]
We are having the same issue ... an anchor tag with href and target blank.
Sometimes headers are added, mostly they aren't.

We add a custom header x-username ...

**Comment by hao1300** [comment]
@yoerivdm have you tried disabling cache as I suggested earlier? https://github.com/bewisse/modheader/issues/47#issuecomment-616576630

**Comment by VictorDurandMeli** [comment]
Hi, i've the same issue and tried disabling cache but don't work.. thanks!

**Comment by hao1300** [comment]
@VictorDurandMeli and anyone else who is experiencing this issue - if you can provide me a URL with some more detail steps to reproduce this issues, that would be great! I cannot fix what I cannot reproduce. If I can reproduce it, I can likely fix it or at least provide a workaround. Thanks!!

**Comment by keittehvan** [comment]
https://codepen.io/keittehvan/pen/JjYmmBr
Just click on the link in this codepen example, no middle nor right click
sometimes the opened site shows headers, sometimes it does not

**Comment by hao1300** [comment]
@keittehvan Thank you!!! I finally figured out the bug thanks to your example! Will publish the new version with the fix shortly. Thank you all!!!
