### ISSUE TITLE
when i jump to a new page , the request for page source didn't show my modheader，modheader version is the newest 。

### ISSUE THREAD

**Issue by Glittergalaxy** [bewisse/modheader#49]

**Comment by hao1300** [comment]
@Glittergalaxy, can you provide me with some more details? When jump to a new page, do you mean opening a new tab? Does it reproduce all all pages or only one page? Can you share the URL to the page you are trying to load? And also your ModHeader profile? Are you seeing that the request headers are not being sent from the dev tool? Can you try "Disable cache" to see if that help?

**Comment by hao1300** [comment]
Closing due to lack of response. Please reopen if needed
