### ISSUE TITLE
Document there are some headers the extension is powerless to modify

### ISSUE THREAD

**Issue by jidanni** [bewisse/modheader#50]
On https://bewisse.com/modheader/ we see

> What can ModHeader do?
> Add/modify/remove request and response headers (you can use this to set X-Forwarded-For, Authorization, Access-Control-Allow-Origin, etc.)

OK, but be sure to also mention what it [cannot](https://medium.com/requestly-docs/list-of-headers-not-allowed-to-be-modified-by-chrome-extensions-c850b5c02fff) do, e.g., modify the incomming Cache-Control header.

**Comment by hao1300** [comment]
Thanks for the suggestions. Added a section on https://bewisse.com/modheader/help/ for this.
