### ISSUE TITLE
Only 1 Active Profile is a Problem

### ISSUE THREAD

**Issue by scott-mcdonald** [bewisse/modheader#51]
I am using ModHeader in _Firefox_ to add API keys to various external API's when using the browser, etc. It is not initially modifying any headers when using from Firefox. Only when I go to ModHeader and **explicitly** select the respective profile does it modify the headers.

In addition, it appears ModHeader only modifies headers for the current **selected** profile, all other profiles are disabled and their headers are not modified.

**Comment by scott-mcdonald** [comment]
I also tried this in _Chrome_ and have the exact same problem I had in _Firefox_. If this is by design where only the selected profile is used then this extension is useless for me...

**Comment by scott-mcdonald** [comment]
Quick question, is ModHeader **designed on purpose** so only 1 profile is active at a time? If so, then it is designed so I should put all my header modifications for discrete HTTP based APIs all in the same profile? If that is so, that is not obvious IMHO...

**Comment by hao1300** [comment]
This is by design currently. Can you give more details about your use case so I can accommodate it in future designs?

**Comment by scott-mcdonald** [comment]
My first instinct was to create a profile for each discrete/independent external API because I am in the business of POS integration of many POS systems. I just thought all profiles were active and a profile was just a logical grouping; when I started using the browser as a "poor man's" REST client tool for GET API calls I noticed the API keys weren't being added, then I figured out only for the current profile an API key was being added. The current profile is the only active profile workflow of your extension wasn't obvious (at least to me) is the main point.

So I guess I'll just create a POS integration profile and put all the POS integration API endpoints in 1 profile, etc. Thanks you can close this issue.

**Comment by scott-mcdonald** [comment]
Actually, I think a better option is to allow the end-user to select which profiles are active? Or have all the profiles active? Each API header key name is different and putting them all in a single profile seems to me it would obfuscate the ModHeader profile and doesn't seem right.

**Comment by scott-mcdonald** [comment]
I will say I like your UI over Requestly which is another HTTP call modifier extension but they allow me to organize things better like I described in the previous comments...

**Comment by hao1300** [comment]
@scott-mcdonald as of v3.1.3, we now support multiple active profiles. You can right click on a profile on the left drawer, and select "Always stay on". This will allow that profile to stay active even when you select another profile, and you will see a green checkbox at the bottom right hand corner.

**Comment by scott-mcdonald** [comment]
@hao1300 I just checked this out and it works as you explained. I was able to hit 2 different API endpoints after activating 2 different profiles, thank you! I'll close the issue...
