### ISSUE TITLE
Allowed Domains

### ISSUE THREAD

**Issue by crazyair** [bewisse/modheader#52]
Can I support setting domains.

To match all sub-domains start the name with a dot. For example .hoo.com will match all sub-domains like news.hoo.com, mail.hoo.com

**Comment by hao1300** [comment]
Yes, you can setup filters with regex, like https://.*.hoo.com/.* will match all subdomains

**Comment by crazyair** [comment]
how use?

**Comment by hao1300** [comment]
Click on +, then select "Filter". In the URL pattern, enter something like
"https://..hoo.com/.*" to match all hoo.com's subdomain and subpaths.
