### ISSUE TITLE
cannot unpause modheader

### ISSUE THREAD

**Issue by jcremy** [bewisse/modheader#53]
Hi,

I'm using Google Chrome 83.0.4103.97 on macos.
My modheader extension seems stuck in pause mode. When I click on the icon, I get a blank popup.

From inpect:

popup.bundle.js:85 

Uncaught (in promise) TypeError: Cannot read property 'slice' of undefined
    at c (popup.bundle.js:85)
    at Object.Mo.t.$$.update (popup.bundle.js:312)
    at kt (popup.bundle.js:1)
    at new Ro (popup.bundle.js:312)
    at Array.Zl (popup.bundle.js:312)
    at p (popup.bundle.js:1)
    at Array.a (popup.bundle.js:62)
    at p (popup.bundle.js:1)
    at a (popup.bundle.js:154)
    at kt (popup.bundle.js:1)

Thanks

**Comment by hao1300** [comment]
Thanks for reporting this. I can't reproduce this so I am not certain of the root cause, but I am pushing out a mitigation in 3.1.5 (should be live by end of day). Please let me know if you still see the bug in the new version.

**Comment by jcremy** [comment]
Just upgraded to 3.1.5. The issue seems fixed.
Thank a lot for your work!

**Comment by linearza** [comment]
Just ran into this again, second time, currently on 3.1.9 - using Brave browser - need to disable the addon, re-enable it, in which case its lost all data, and I need to restore it from cloud backup.

**Comment by kgkapasi23** [comment]
Hi, this issue is still happening. My mod header version is 3.1.22
