### ISSUE TITLE
Several buttons missing in UI in Linux

### ISSUE THREAD

**Issue by grubersjoe** [bewisse/modheader#60]
I'm using the addon in Firefox v80 in Arch Linux. For some reason several buttons next to the profile heading are missing. On Mac OS this does not happen.

![grafik](https://user-images.githubusercontent.com/3109364/92582079-cc98cd80-f290-11ea-8934-550d4b8cdb43.png)

This way I'm unable to add new headers in the current profile and have to create another profile for every header I want to set. Any idea what's wrong here?

**Comment by hao1300** [comment]
Sorry I am not sure what is happening. The icons on the top are supposed to be rendered in a similar way as the icons on the left bar. Not sure why they don't show up.

**Comment by the-j0k3r** [comment]
Arch Linux is a rolling release that contains bleeding edge (alpha/beta) libs, etc, oddities are to be expected here and there and everywhere. I would be interested in the @grubersjoe  response to issue on other Linux non rolling release, say test Ubuntu or Debian or similar.

Re this, perhaps check the source for AUR for Firefox and ensure thats being built against the default libs versions the maintainer would be able to say something, At time of writing Firefox is version 83. 

That or compile the most recent Firefox source yourself. ;)
