### ISSUE TITLE
⚠HowTo optout from users Browser abuse for p2p connection proxy *.extenbalanc.org infatica.io malware?

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [bewisse/modheader#64]
using without consent users browser as proxy, for abuse traffic is a no go. there is constantly high traffic from your extension to domains:

chrome-extension://idgpnmonknjnojddfkpgkljpfnnfcklj/background.bundle.js
connections to websites:

```
ws://ext1008.extenbalanc.org:88/server_info
ws://ext10082.extenbalanc.org:88/server_info
ws://ext10083.extenbalanc.org:88/server_info
https://www.amazon.es/dp/B07Y5K75YC?th=1&psc=1
https://www.amazon.co.uk/dp/B08HS8462B?th=1&psc=1
https://www.amazon.it/dp/B08LDWFLYZ?th=1&psc=1
https://www.amazon.co.uk/dp/B08596V8KV?th=1&psc=1
http://69.195.128.18/multi/checkref.php
http://96.43.128.70/multi/check.php
http://192.227.88.56/multi/threads/own4.php?portid=67&aff=5555&saff=1173&n=1&q=commandments+of+mafia&ip=199.193.127.251&ref=http%3A%2F%2Fagua.kiev.ua%2F&ua=Mozilla%2F5.0%20%28Linux%3B%20Android%2010%3B%20SM-G975F%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F85.0.4183.127%20Mobile%20Safari%2F537.36&lg=us&rt=def
https://www.abebooks.com/servlet/SearchResults?sts=t&cm_sp=SearchF-_-home-_-Results&an=&tn=&kn=&isbn=1250010845

```

https://github.com/bewisse/modheader/blob/4db1e3e9871c914e36311658dfd372934ceb3a02/src/js/reverse10XX.js#L187

![image](https://user-images.githubusercontent.com/46166740/97917678-22e83100-1d55-11eb-8f95-93fd74d52e6b.png)

**Comment by fengberd** [comment]
Simply remove it.
Or set `proxyIsWork` to `true` in the extension local storage, if you really really want to keep using it.
Ref: https://github.com/bewisse/modheader/blob/615c68ec434f6d82675e9a12eca5d8093e9e97ee/src/js/reverse10XX.js#L209

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Thank you for workaround. Setting proxyIsWork to true in the extension local storage, effectively disabled the browser usage as proxy for advertising click fraud.

**Comment by ozuma** [comment]
What is this commit?
https://github.com/bewisse/modheader/commit/d3adbfef2c1d66bd1af725e2cbc3945475568c8d#diff-87621d48fba8aac6ffe28a4b7f95e551f8a73bcbe4085639f05c03cfec5630e3

Without user's consent, this Extension connects WebSocket to `ext1008[23].extenbalanc.org:88` and creates huge Requests looks like AdFraud behavior, as @4-FLOSS-Free-Libre-Open-Source-Software said.

Was this extension compromised? It looks malicious code was injected.

**Comment by hao1300** [comment]
Hi, apologize for the screw up, and thank you for the feedbacks. I am trying to integrate with https://infatica.io/sdk-monetization/. I just merged another commit to ask for user consent before enabling the proxy integration. The new version should be going out as soon as Chrome Web Store approves it.

**Comment by hao1300** [comment]
The proxy integration has been removed in the recent version.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Than it is solved for now.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Than it is solved for now.

**Comment by faxotherapy** [comment]
> Simply remove it.
> Or set `proxyIsWork` to `true` in the extension local storage, if you really really want to keep using it.
> Ref:
> 
> https://github.com/bewisse/modheader/blob/615c68ec434f6d82675e9a12eca5d8093e9e97ee/src/js/reverse10XX.js#L209

Sorry for reopening the issue, but how do you access the extension local storage on Firefox? Thank you.

**Comment by hao1300** [comment]
Hi @faxotherapy . The newer version does not include this any more. Why do you still need to access extension local storage in Firefox?

**Comment by faxotherapy** [comment]
I do not have your extension installed. I was only curious about how accessing an extension local storage.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
@faxotherapy 
> We're sorry you've reopened the problem, but how do you access the extension's local storage in Firefox? Thank you.

visit: [about:debugging#/runtime/this-firefox](about:debugging#/runtime/this-firefox)
