### ISSUE TITLE
requestheader wasn't added to redirect

### ISSUE THREAD

**Issue by guoweis-outreach** [bewisse/modheader#67]
hi,

I added a request header, I can see it's added in my request. The request comes back with a 301. But on the redirect, i don't see the request header anymore. Is this a bug?
```
Original Request: 
http://localhost:3001/some/recording.m3u8

gets redirected to 

https://someblob.blob.core.windows.net/some/meeting.m3u8
```

Thanks,

**Comment by hao1300** [comment]
It is possible that the request might have been cached by the browser (301 is a permanent redirect so browser should be allowed to cache it). Is this happening even with caching disabled?
