### ISSUE TITLE
no header if value field is empty

### ISSUE THREAD

**Issue by bbvveli** [bewisse/modheader#68]
In some cases people may want to send http headers with empty value in request. 

**Problem:** In the pop-up if I leave the value field empty, header wont be added to request. If I enter a space char, then it will be added in request headers.

Must: Add header to request if value field is empty but key has characters.

**Comment by hao1300** [comment]
Can you click on the ... on the top-right hand corner, and change the "Empty header mode" to "Send empty header"?

**Comment by bbvveli** [comment]
> Can you click on the ... on the top-right hand corner, and change the "Empty header mode" to "Send empty header"?

oh thanks for the hint. I missed that option, I was checking. the setting apperantly.
