### ISSUE TITLE
URL pattern starting with wildcard (*)

### ISSUE THREAD

**Issue by peanutsmcgee** [bewisse/modheader#69]
`*.domain.com` does not work. It seems that having a wildcard as the first character doesn't read correctly.

Pre-pending it with a dummy character like a blank space makes it work, e.g. `  *.domain.com `

**Comment by hao1300** [comment]
It is a JS style regex pattern, so you actually need something like `.*.domain.com` where `.` means any character, and `.*` means any number of characters in the prefix.

**Comment by peanutsmcgee** [comment]
Oh I see. So i would actually need `.*\.domain\.com` right? Since I want the other dogs to be string literals

**Comment by hao1300** [comment]
Yes
