### ISSUE TITLE
Header containing foreign characters is skipped

### ISSUE THREAD

**Issue by smoksnes** [bewisse/modheader#71]
When having a header which contains foregin characters such as ÅÄÖ ModHeader will remove the header (even though ModHeader is not managing this header)

Tested on Chrome 88.0.4324.104 (x64)
Reproducable jsfiddle here: http://jsfiddle.net/qr8j0cgo/

**Comment by hao1300** [comment]
I tried the example without ModHeader and the foreign header value is not sent either. I think the filtering is done in Chrome, not ModHeader
