### ISSUE TITLE
Settings and values not saved on Firefox Developer Edition 

### ISSUE THREAD

**Issue by nicksemansonos** [bewisse/modheader#72]
# Environment

- Firefox Developer Edition 86.0b6 (64-bit)
- macOS 10.15.7

# Issue
All settings, values, and other information are not saved when the extension is closed.

# Expected behavior
All settings, values, and any changes made would be saved when the extension is closed.

# Reproduction steps
1. Install ModHeader addon in Firefox Developer Edition.
2. Open the extension, fill in "test" for the values, or select "Value concatenation" from the menu.
3. Close the extension.
4. Reopen the extension. Observe the values are missing, and the setting has returned to default.

# Troubleshooting
1. Test removing/re-adding the extension.
2. Test clearing all local extension storage.
3. Test fully resetting Firefox browser profile.

The problem persists.

# Other info
Firefox 85.0 on the same Mac works without issue. I have gotten it occasionally to save the very first set of values and settings on reinstall, but any subsequent reopening of the extension results in this same error and the values cannot be edited.

This is what's in the `console.log` if I debug the add-on while closing the extension window.

```
TypeError: can't access property "innerWindowId", win.windowGlobalChild is null
storage.js:3524:18
    getWindowFromInnerWindowID resource://devtools/server/actors/storage.js:3524
    observe resource://devtools/server/actors/storage.js:3566
can't access dead object ExtensionStorage.jsm:91
    serialize resource://gre/modules/ExtensionStorage.jsm:91
    set resource://gre/modules/ExtensionStorageIDB.jsm:252
    InterpretGeneratorResume self-hosted:1484
    AsyncFunctionNext self-hosted:690
Uncaught (in promise) Error: An unexpected error occurred
```

**Comment by sean0x42** [comment]
This is also happening for me in regular Firefox. Sometimes it seems to work, most of the time it fails.

- Firefox 85.0.2 (64 bit)
- MacOS 11.0.1

**Comment by pdawson** [comment]
Same for me on Firefox Developer Edition 87.0b2

It's been doing it off and on for a while now. Sometimes it saves without error, others it can take around 10 attempts to get the values to change.

**Comment by ronappleton** [comment]
I stopped using it in chrome a long time ago now for this exact reason.

**Comment by hao1300** [comment]
Thanks for the report. Sorry for the delayed response. Looking into this now

**Comment by hao1300** [comment]
A new version has been published on Firefox to improve the reliability of the saving operation. Hope that helps.

**Comment by nicksemansonos** [comment]
Seems to be saving values and settings reliably now for me. Thank you!
