### ISSUE TITLE
[bug] profile dropdown broken, profile bar isn't wide enough for icons

### ISSUE THREAD

**Issue by Favna** [bewisse/modheader#83]
Hello there,

As of about a week ago or so when opening ModHeader the bar that shows the profiles is too small to properly fit the icon of a profile. My profile labels are all 1 letter, so that is not the problem. 

I have been able to reproduce this issue in Microsoft Edge (version 91.0.864.37) and in Chrome (version 91.0.4472.77) and I have also determined several colleagues of mine are facing the same issue.

![image](https://user-images.githubusercontent.com/4019718/120832310-cce4a180-c560-11eb-9ed5-36dfdcdd07b2.png)

**Comment by TerraSkye** [comment]
im facing the same issue.

**Comment by hao1300** [comment]
I committed a fix: https://github.com/bewisse/modheader/commit/032d8e4acfb6d2aed6af27f7066fd17421395599. Waiting to publish the update.

**Comment by Favna** [comment]
@hao1300 waiting to publish in what terms exactly? Because the Chrome webstore lists 3.1.22 but your commit goes from 3.1.23 to 3.1.24 so there is already 1 other unpublished version in between. If you mean that you need the latest commit to be tested then please let me know and I'll build chrome and edge locally and test them.

**Comment by hao1300** [comment]
You will need to build it locally if you want it fixed sooner. I tried to publish 3.1.23 last week, but it is still pending review in Chrome Web Store and on Edge. Once that gets published, then I can release 3.1.24, which again will need to go through Chrome and Edge review process.

I don't control how fast / slow these review processes will take. Google and Microsoft control them. Sometimes it only takes a few hours. Sometimes it can take a few days or even a few weeks.

**Comment by Favna** [comment]
ah okay, thanks for clarifying. I've never dabbled in chrome extensions or its the review process. I'll inform my team members that the fix is soon-ish to be available.

**Comment by hao1300** [comment]
The release finally went out.
