### ISSUE TITLE
Possibility to sort profiles

### ISSUE THREAD

**Issue by zayats103** [bewisse/modheader#9]
Hi!

As I understand, right now Profiles are sorted by creation date. It would be nice to change sorting field (to sort Profiles by name) and change sorting order.
Probably it would be great to have a search possibility in Profiles and automatically focus search input when profiles are opened, but I am not sure if anybody has so many profiles so they don't fit in the window.

**Comment by hao1300** [comment]
Hi, you can sort profiles by clicking on 'Name' or 'Value' at the top.

**Comment by zayats103** [comment]
> Hi, you can sort profiles by clicking on 'Name' or 'Value' at the top.

You are talking about request/response headers inside the profiile. In profile list there is no columns like 'Name' or 'Value', there are just checkboxes and profile names (see screenshot http://prntscr.com/otjcwb). I am talking about sorting Profiles (not headers)

**Comment by hao1300** [comment]
ah, I see. Yes, that feature isn't available. I just didn't think users would have more than a handful of profiles for sorting to be useful.

**Comment by zayats103** [comment]
> ah, I see. Yes, that feature isn't available. I just didn't think users would have more than a handful of profiles for sorting to be useful.

In our case we use headers with different values depending on use-case and it could be up to 20-30 use cases and we make 1 profile for each use case. 
So sometimes it is quite hard to find needed profile so we will appreciate possibility to sort profiles :)

**Comment by zayats103** [comment]
@hao1300 Is it possible to add support for this? Should issue be reopened?

**Comment by hao1300** [comment]
I don't think I will support this any time soon, but feel free to send me a pull request to add support for it.

**Comment by hao1300** [comment]
Just released a new version with the implementation from @zskullz's PR.
