### ISSUE TITLE
How to use modheader in puppeter and load profile

### ISSUE THREAD

**Issue by djlshk** [bewisse/modheader#92]
I already have a pupeter program and want to add modheader, but I don't know how to import the existing configuration file. I started the browser with pupeteer.lunach and loaded the modheader through -- load extension, but I can't set the header.
Or is there any other way to use modheader directly

**Comment by hao1300** [comment]
Can you try using https://github.com/bewisse/modheader_selenium? If you install that extension, you can navigate to specific URLs to add the headers
